name: CI

on: 

  push:
    branches: [ "feature-ms-AlexisGhio-mensaje" ]
  pull_request:
    branches: [ "feature-ms-AlexisGhio-mensaje" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "hola mundo"
